ARG CUDA_VERSION=13.0.2
ARG PYTHON_VERSION=3.12.10

FROM nvidia/cuda:${CUDA_VERSION}-devel-ubuntu24.04 AS base

RUN apt update -y && \
    apt install -y --no-install-recommends \
    build-essential \
    curl \
    zlib1g

RUN CUDA_VERSION_DASH=$(echo $CUDA_VERSION | cut -d. -f1,2 | tr '.' '-') && CUDA_MAJOR_VERSION=$(echo $CUDA_VERSION | cut -d. -f1) && \
    apt update -y && \
    apt install -y --no-install-recommends \
        build-essential \
        cuda-nvcc-${CUDA_VERSION_DASH} \
        cuda-cudart-${CUDA_VERSION_DASH} \
        cuda-nvrtc-${CUDA_VERSION_DASH} \
        cuda-cuobjdump-${CUDA_VERSION_DASH} \
        libcurand-dev-${CUDA_VERSION_DASH} \
        libcublas-${CUDA_VERSION_DASH} \
        cudnn9-cuda-${CUDA_MAJOR_VERSION}

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
ENV UV_LINK_MODE=copy

WORKDIR /yasha

ADD ./pyproject.toml pyproject.toml
ADD ./README.md README.md
ADD ./uv.lock uv.lock

ENV UV_PROJECT_ENVIRONMENT=/.venv
ENV VIRTUAL_ENV=/.venv
RUN uv venv

ARG PYTHON_VERSION
RUN uv python install ${PYTHON_VERSION}
RUN uv pip install onnxruntime-gpu==1.19.2

ENV PATH="$UV_PROJECT_ENVIRONMENT/bin:$PATH"

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked --no-install-project

# # just in case we decide to copy the project here
# # RUN --mount=type=cache,target=/root/.cache/uv \
# #     uv sync --locked

WORKDIR /
COPY <<EOF start.sh
#!/bin/bash
# echo "Available ONNX Providers: $(python -c 'import onnxruntime as ort; print(ort.get_available_providers())')"

uv sync --project /yasha --locked

cd /yasha && ray start --head --dashboard-port=\${RAY_DASHBOARD_PORT} --port=\${RAY_REDIS_PORT} --dashboard-host=0.0.0.0 --num-cpus=\${RAY_HEAD_CPU_NUM} --num-gpus=\${RAY_HEAD_GPU_NUM} --disable-usage-stats
if ray status --address=0.0.0.0:\${RAY_REDIS_PORT}; then
    /bin/bash
    # if serve start --http-host 0.0.0.0 --http-port 8000; then
    #     if timeout -k 30 20 serve status --address=http://0.0.0.0:\${RAY_DASHBOARD_PORT}; then
    #         echo "ray serve started"
    #         # serve run --route-prefix=/ --name='yasha api' --working-dir=/yasha --address=0.0.0.0:\${RAY_REDIS_PORT} --blocking start:app
    #         /bin/bash
    #     else
    #         echo "ray serve failed to start"
    #     fi
    # fi
else
    echo "ray cluster failed to start"
fi

EOF
RUN chmod +x start.sh

WORKDIR /
CMD ["uv", "run", "--active", "bash", "start.sh"]





