ARG CUDA_VERSION=12.9.1
ARG CODE_SERVER_VERSION=4.107.0
ARG PYTHON_VERSION=3.12.10

FROM nvidia/cuda:${CUDA_VERSION}-devel-ubuntu22.04 AS base

RUN apt update -y && \
    apt install -y --no-install-recommends \
    build-essential \
    curl \
    zlib1g

ARG CODE_SERVER_VERSION
# install code server
WORKDIR /root
RUN curl -fOL https://github.com/coder/code-server/releases/download/v${CODE_SERVER_VERSION}/code-server_${CODE_SERVER_VERSION}_amd64.deb
RUN dpkg -i code-server_${CODE_SERVER_VERSION}_amd64.deb
RUN mkdir -p .config/code-server 
COPY <<EOF .config/code-server/config.yaml
bind-addr: 0.0.0.0:8080
auth: none
password: f33b6f3a39732a93379c37b8
cert: false
EOF
RUN code-server --install-extension ms-python.python
RUN code-server --install-extension ms-pyright.pyright

RUN CUDA_VERSION_DASH=$(echo $CUDA_VERSION | cut -d. -f1,2 | tr '.' '-') && CUDA_MAJOR_VERSION=$(echo $CUDA_VERSION | cut -d. -f1) && \
    apt update -y && \
    apt install -y --no-install-recommends \
        build-essential \
        cuda-nvcc-${CUDA_VERSION_DASH} \
        cuda-cudart-${CUDA_VERSION_DASH} \
        cuda-nvrtc-${CUDA_VERSION_DASH} \
        cuda-cuobjdump-${CUDA_VERSION_DASH} \
        libcurand-dev-${CUDA_VERSION_DASH} \
        libcublas-${CUDA_VERSION_DASH} \
        cudnn9-cuda-${CUDA_MAJOR_VERSION}

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
ENV UV_LINK_MODE=copy

WORKDIR /yasha

ADD ./pyproject.toml pyproject.toml
ADD ./README.md README.md
ADD ./uv.lock uv.lock

ENV UV_PROJECT_ENVIRONMENT=/yasha/.venv
RUN uv venv

ARG PYTHON_VERSION
RUN uv python install ${PYTHON_VERSION}
RUN uv pip install onnxruntime-gpu==1.19.2

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked --no-install-project

# # just in case we decide to copy the project here
# # RUN --mount=type=cache,target=/root/.cache/uv \
# #     uv sync --locked

ENV PATH="$UV_PROJECT_ENVIRONMENT/bin:$PATH"

WORKDIR /yasha
COPY <<EOF start.sh
#!/bin/bash
code-server &

uv sync --locked

ray start --head --dashboard-port=\${RAY_DASHBOARD_PORT} --port=\${RAY_REDIS_PORT} --dashboard-host=0.0.0.0 --num-cpus=8 --num-gpus=1 --disable-usage-stats
if ray status --address=0.0.0.0:\${RAY_REDIS_PORT}; then
    uv run --active start.py
else
    echo "ray cluster failed to start"
fi

EOF
RUN chmod +x start.sh

WORKDIR /yasha
CMD ["uv", "run", "bash", "start.sh"]





