# vllm engine args reference: https://docs.vllm.ai/en/latest/configuration/engine_args.html

models:
  -
    name: "Llama-3.1-8B"
    vllm_engine_kwargs:
      model: "unsloth/Meta-Llama-3.1-8B-Instruct-bnb-4bit"
      # model: "unsloth/Llama-3.2-1B-Instruct-bnb-4bit"
      tensor_parallel_size: 1
      max_model_len: 40000
      gpu_memory_utilization: 0.75
      task: "generate"
  - 
    name: "nomic-embed-text-v1.5"
    vllm_engine_kwargs:
      model: "nomic-ai/nomic-embed-text-v1.5"
      tensor_parallel_size: 1
      task: "embed"
      gpu_memory_utilization: 0.1
      trust_remote_code: 1
