ARG PYTHON_VERSION

FROM vllm/vllm-openai:v0.10.0

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
ENV UV_LINK_MODE=copy

RUN uv pip install --system vllm[audio]==0.10.0
# RUN uv pip install --system git+https://github.com/huggingface/transformers.git
RUN uv pip install --system transformers==4.53.2

# Change the working directory to the `app` directory
WORKDIR /yasha

# Install dependencies
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --no-install-project

# Copy the project into the image
ADD . /yasha

# Sync the project
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked

ENV PATH="/yasha/.venv/bin:$PATH"

ENTRYPOINT ["/usr/bin/env"]
