ARG PYTHON_VERSION

FROM vllm/vllm-openai:v0.12.0

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
ENV UV_LINK_MODE=copy

RUN uv pip install --system vllm[audio]==0.12.0

# Change the working directory to the `app` directory
WORKDIR /

# Install dependencies
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --no-install-project

# Copy the project into the image
ADD ./yasha /yasha
ADD ./pyproject.toml /pyproject.toml
ADD ./README.md /README.md
ADD ./uv.lock /uv.lock
ADD ./.env /.env
ADD ./api.py /api.py

# Sync the project
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked

ENV PATH="/.venv/bin:$PATH"

ENTRYPOINT ["/usr/bin/env"]
