# vllm engine args reference: https://docs.vllm.ai/en/latest/configuration/engine_args.html

models:
  -
    name: "kokoro"
    model: "hexgrad/Kokoro-82M"
    usecase: "tts"
    loader: "custom"
    plugin: "kokoro"
    num_gpus: 0.1
    plugin_config:
      onnx_provider: "CUDAExecutionProvider"

  -
    name: "whisper"
    model: "openai/whisper-small"
    usecase: "transcription"
    loader: "vllm"
    num_gpus: 0.15
    vllm_engine_kwargs:
      trust_remote_code: 1

  -
    name: "nomic-embed-text-v1.5"
    model: "nomic-ai/nomic-embed-text-v1.5"
    usecase: "embed"
    loader: "vllm"
    num_gpus: 0.05
    vllm_engine_kwargs:
      trust_remote_code: 1

  # -
  #   name: "bark-small"
  #   model: "suno/bark-small"
  #   usecase: "tts"
  #   loader: "custom"
  #   plugin: "bark"
  #   num_gpus: 0.3

  # -
  #   name: "orpheus"
  #   model: "unsloth/orpheus-3b-0.1-ft-unsloth-bnb-4bit"
  #   usecase: "tts"
  #   loader: "custom"
  #   plugin: "orpheus"
  #   num_gpus: 0.5
  #   plugin_config:
  #     gpu_memory_utilization: 0.5
  #     max_model_len: 2048
  #     dtype: "float16"
  #     kv_cache_dtype: "fp8_e4m3"
  #     quantization: "fp8"

  -
    name: "llama-3.1"
    model: "neuralmagic/Meta-Llama-3.1-8B-Instruct-FP8-dynamic"
    usecase: "generate"
    loader: "vllm"
    vllm_engine_kwargs:
      max_model_len: 32000
      enable_log_requests: 1
      enable_auto_tool_choice: 1
